#!/usr/bin/env python3
"""Interactive flash parameter setter.

Prompts only for flash-related parameters (`PROG`, `PROG_BAUD`, `PORT`) and
merges them into `include/last_build.make`. Intended to be invoked via
`make flash_interactive`.
"""
import os
import re

ROOT = os.path.abspath(os.path.dirname(os.path.dirname(__file__)))
OUT = os.path.join(ROOT, 'include', 'last_build.make')

COMMON_PROGS = ['arduino', 'stk500v1', 'stk500v2', 'usbasp', 'usbtiny', 'avrisp', 'avr109']


def load_existing(path):
    vals = {}
    if not os.path.exists(path):
        return vals
    with open(path, 'r') as f:
        for ln in f:
            m = re.match(r'^\s*([A-Za-z0-9_]+)\s*[:?]?=\s*(.*)$', ln)
            if m:
                k = m.group(1).strip()
                v = m.group(2).strip()
                vals[k] = v
    return vals


def prompt_simple(key, cur):
    prompt_text = f"{key} [{cur}]: " if cur != '' else f"{key} []: "
    val = input(prompt_text).strip()
    return val if val != '' else cur


def choose_from_list(prompt_text, options, cur):
    print(prompt_text)
    for i, opt in enumerate(options, start=1):
        print(f"  {i}) {opt}")
    sel = input(f"Choose [1-{len(options)}] or enter value [{cur}]: ").strip()
    if sel == '':
        return cur
    if sel.isdigit():
        idx = int(sel)
        if 1 <= idx <= len(options):
            return options[idx - 1]
    return sel


def main():
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    existing = load_existing(OUT)

    ex_prog = existing.get('PROG', '')
    prog = choose_from_list('Select programmer (or type custom):', COMMON_PROGS, ex_prog)

    ex_baud = existing.get('PROG_BAUD', '115200')
    prog_baud = prompt_simple('PROG_BAUD', ex_baud)

    ex_port = existing.get('PORT', '/dev/ttyUSB1')
    port = prompt_simple('PORT', ex_port)

    # Merge with existing keys so we don't clobber other build settings
    merged = dict(existing)
    merged['PROG'] = prog
    merged['PROG_BAUD'] = prog_baud
    merged['PORT'] = port

    with open(OUT, 'w') as f:
        f.write('# Generated by tools/interactive_flash.py\n')
        for k in sorted(merged.keys()):
            f.write(f"{k} = {merged[k]}\n")

    print('Wrote', OUT)

    run_now = input('Run flash now? [Y/n]: ').strip().lower()
    if run_now in ('', 'y', 'yes'):
        os.execvp('make', ['make', 'flash'])


if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        print('\nInterrupted.')
        raise
